{% set name = "stack_data" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7769ed2482ce0030e00175dd1bf4ef1e873603b6ab61cd3da443b410e64e9477

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=44
    - setuptools_scm >=3.4.3
  run:
    - asttokens
    - executing
    - pure_eval
    - python >=3.5

test:
  imports:
    - stack_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/alexmojaki/stack_data
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Extract data from python stack frames and tracebacks for informative displays
  doc_url: http://github.com/alexmojaki/stack_data
  dev_url: http://github.com/alexmojaki/stack_data

extra:
  recipe-maintainers:
    - alexmojaki
